import './public/static/courses.scss'
import './public/static/educationalBackground.scss'
import './public/static/footer.scss'
import './public/static/global.scss'
import './public/static/header.scss'
import './public/static/landingPage.scss'
import './public/static/main.scss'
import './public/static/skills.scss'

import './public/src/header.js'
import './public/src/transitionHidden.js'